- hosts: server1
  become: yes
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: id_rsa

  tasks:
  - name: Run the bash script to create DB
    shell: /home/ubuntu/sqldb.sh
    args:
      executable: /bin/bash
    register: result
  - name: Display script output
    debug:
      var: result
